- lib/home_screen.dart
- lib/main.dart
Create HomeScreen that offers a bottom bar for changing screen
> Home screen

- lib/home_screen.dart
- lib/music_player/labeled_slider.dart
- lib/music_player/loop_card/loop_slider.dart
- lib/music_player/music_player_screen.dart
- lib/music_player/pitch_speed_card.dart
- lib/tuner/tuner_screen.dart
Update how the pitch and speed sliders look. 
Only have one reset button.
Display max and min instead of current value.
Add current value as a label to the sliders.
> Pitch & speed sliders

- android/app/src/main/AndroidManifest.xml
- lib/metronome/beat_sound_viewer.dart
- lib/metronome/bpm_tapper.dart
- lib/metronome/metronome_beats.dart
Add haptic feedback to some actions.
> Haptic feedback

- lib/tuner/tuner.dart
- lib/tuner/tuner_screen.dart
Create Tuner singleton which handles getting audio from the microphone and detecting the pitch.
> Create Tuner singleton

- .metadata
- lib/editable_screen/card_list.dart
- lib/main.dart
- lib/metronome/metronome_screen.dart
- lib/music_player/music_player_screen.dart
- lib/navigation_screen.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
Add App bar with button for opening info dialog to every screen.
Info dialog includes general app info, licenses and a short help text how to use the screen.
> Info dialog

- lib/tuner/tuner.dart
- lib/tuner/tuner_gauge.dart
- lib/tuner/tuner_screen.dart
- lib/tuner/tuning_graph.dart
- pubspec.yaml
Create a graph showing how the tuning changes over time.
Tuning is shown as a line.
Text labels show what note it is.
The section where the note is in tune is highlighted in green.
Also let Tuner singleton handle averaging when a new pitch is detected.
Cleanup Tuner singleton.
If no pitch has been detected, TunerGauge displays "listening" text.
> Tuning graph

- lib/music_player/current_song_card/youtube_button.dart
- lib/music_player/music_player.dart
- pubspec.lock
- pubspec.yaml
> Escape HTML characters in YouTube title

- lib/main.dart
- lib/tuner/tuner_gauge.dart
- lib/tuner/tuning_graph.dart
> Update the colors used on TunerScreen

- lib/main.dart
- lib/metronome/beat_sound.dart
- lib/tuner/tuner_gauge.dart
- lib/tuner/tuning_graph.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
Dynamically set the color scheme based on colors from the device
> Dynamic color

- lib/main.dart
- lib/music_player/current_song_card/current_song_panel.dart
- lib/music_player/current_song_card/pick_song_button.dart
- lib/permission_builder.dart
- lib/tuner/tuner.dart
- lib/tuner/tuner_screen.dart
- pubspec.lock
- pubspec.yaml
Handle permissions.
Create PermissionBuilder for letting the user grant or deny a permission.
Use it for Tuner and PickSongButton.
> Permission

- lib/music_player/current_song_card/youtube_api/thumbnails.dart
- lib/music_player/current_song_card/youtube_api/video.dart
- lib/music_player/current_song_card/youtube_api/youtube_api.dart
- lib/music_player/current_song_card/youtube_button.dart
- pubspec.lock
Display a short help text below the Youtube search bar if the search history is empty
> Youtube search help text

- lib/metronome/bpm_buttons.dart
- lib/music_player/music_player_screen.dart
- lib/music_player/position_card/button_panel.dart
- lib/widgets.dart
Add a button for restarting the song from the beginning.
Holding down the seek buttons causes multiple consecutive presses.
> Restart button

- lib/metronome/bpm_tapper.dart
- lib/widgets.dart
> Decrease the delay when pressing BpmTapper

- lib/navigation_screen.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
Setup in-app review using package advanced_in_app_review
> In-app review

- lib/music_player/card_header.dart
- lib/music_player/demixer/demixer_card.dart
- lib/music_player/equalizer/equalizer_card.dart
- lib/music_player/looper/loop_card.dart
- lib/music_player/slowdowner/slowdowner_card.dart
Create CardHeader widget to reduce duplicate code
> CardHeader

- lib/music_player/current_song_card/current_song_panel.dart
- lib/music_player/current_song_card/pick_song_button.dart
- lib/music_player/current_song_card/song_history_list.dart
- lib/music_player/current_song_card/youtube_button.dart
- lib/music_player/exception_dialogs.dart
- lib/music_player/music_player.dart
- lib/music_player/music_player_screen.dart
- lib/music_player/song_source.dart
- lib/navigation_screen.dart
Show a dialog when the loading of a file or Youtube video failed.
> Loading song failed Dialog

- lib/metronome/metronome_beats.dart
- lib/music_player/current_song_card/youtube_api/youtube_api.dart
- lib/music_player/demixer/demixer.dart
- lib/music_player/demixer/demixer_api.dart
- lib/music_player/demixer/demixing_process.dart
- lib/music_player/demixer/host.dart
- lib/music_player/looper/looper.dart
- lib/music_player/song_history.dart
- lib/music_player/song_source.dart
Cache Youtube song audio and demixed stems
> Cache audio

- lib/music_player/music_player.dart
> music-player/issue72/configure-audio-session

- lib/main.dart
- lib/navigation.dart
- lib/songs/analyzer/analyzer_card.dart
- lib/songs/analyzer/chords_display.dart
- lib/songs/analyzer/waveform_widget.dart
- lib/songs/demixer/demixer_card.dart
- lib/songs/library_page/youtube_search.dart
- lib/songs/song_page/button_panel.dart
- lib/songs/song_page/position_slider.dart
- lib/songs/song_page/song_page.dart
- lib/utils/loading.dart
- lib/widgets/flat_card.dart
- lib/widgets/segmented_tab_control/segmented_tab_control.dart
Create a shimmer effect to clearly indicate when content is loading.
The effect has only been applied to the Song player thus far. Coming PRs should use it for the other tools as well.
> Shimmer loading effect

- lib/main.dart
- lib/navigation.dart
- lib/songs/analyzer/analyzer_card.dart
- lib/songs/analyzer/chords_display.dart
- lib/songs/analyzer/waveform_widget.dart
- lib/songs/demixer/demixer_card.dart
- lib/songs/library_page/youtube_search.dart
- lib/songs/song_page/button_panel.dart
- lib/songs/song_page/position_slider.dart
- lib/songs/song_page/song_page.dart
- lib/utils/loading.dart
- lib/widgets/flat_card.dart
- lib/widgets/segmented_tab_control/segmented_tab_control.dart
Create a shimmer effect to clearly indicate when content is loading.
The effect has only been applied to the Song player thus far. Coming PRs should use it for the other tools as well.
> Shimmer loading effect (re-merge)
